name: 'Auto Assign'
on:
  pull_request:
    branches:
      - master  # when the PR destination is master, executed this workflow

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: ".github/auto_assign.yml"
